#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : nlopt
Version  : 2.4.2
Release  : 13
URL      : http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz
Source0  : http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz
Summary  : nonlinear optimization libary
Group    : Development/Tools
License  : MIT LGPL-2.1
Requires: nlopt-lib
Requires: nlopt-doc
BuildRequires : python
BuildRequires : python-dev

%description
NLopt is a library for nonlinear local and global optimization, for
functions with and without gradient information.  It is designed as
as simple, unified interface and packaging of several free/open-source
nonlinear optimization libraries.

%package dev
Summary: dev components for the nlopt package.
Group: Development
Requires: nlopt-lib

%description dev
dev components for the nlopt package.


%package doc
Summary: doc components for the nlopt package.
Group: Documentation

%description doc
doc components for the nlopt package.


%package lib
Summary: lib components for the nlopt package.
Group: Libraries

%description lib
lib components for the nlopt package.


%prep
%setup -q -n nlopt-2.4.2

%build
%configure --disable-static --enable-shared
make V=1 %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/include/*.hpp
/usr/include/nlopt.f
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
